CREATE DATABASE yeticave
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

USE yeticave;

CREATE TABLE categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  email VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  contacts TEXT NOT NULL,
  avatar VARCHAR(255)
);

CREATE TABLE lots (
  id INT AUTO_INCREMENT PRIMARY KEY,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  title VARCHAR(128) NOT NULL,
  description TEXT NOT NULL,
  image VARCHAR(255) NOT NULL,
  category_id INT NOT NULL,
  price INT NOT NULL,
  end_time TIMESTAMP NULL,
  step_rate INT NOT NULL,
  user_id INT NOT NULL,
  winner_id INT
);

ALTER TABLE lots ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE lots ADD FOREIGN KEY (winner_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE lots ADD FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE;

CREATE TABLE bets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  rate INT NOT NULL,
  user_id INT NOT NULL,
  lot_id INT NOT NULL
);

ALTER TABLE bets ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE bets ADD FOREIGN KEY (lot_id) REFERENCES lots(id) ON DELETE CASCADE;

